export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";

export const LOGOUT = "LOGOUT";

export const ALL_BRANCHES_REQUEST = "ALL_BRANCHES_REQUEST";
export const ALL_BRANCHES_SUCCESS = "ALL_BRANCHES_SUCCESS";
export const ALL_BRANCHES_FAILURE = "ALL_BRANCHES_FAILURE";

export const ALL_SUPPLIER_REQUEST = "ALL_SUPPLIER_REQUEST";
export const ALL_SUPPLIER_SUCCESS = "ALL_SUPPLIER_SUCCESS";
export const ALL_SUPPLIER_FAILURE = "ALL_SUPPLIER_FAILURE";

export const SCAN_PRODUCT_REQUEST = "SCAN_PRODUCT_REQUEST";
export const SCAN_PRODUCT_SUCCESS = "SCAN_PRODUCT_SUCCESS";
export const SCAN_PRODUCT_FAILURE = "SCAN_PRODUCT_FAILURE";
