export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";

export const LOGOUT = "LOGOUT";

export const ALL_BRANCHES_REQUEST = "ALL_BRANCHES_REQUEST";
export const ALL_BRANCHES_SUCCESS = "ALL_BRANCHES_SUCCESS";
export const ALL_BRANCHES_FAILURE = "ALL_BRANCHES_FAILURE";

export const ALL_SUPPLIER_REQUEST = "ALL_SUPPLIER_REQUEST";
export const ALL_SUPPLIER_SUCCESS = "ALL_SUPPLIER_SUCCESS";
export const ALL_SUPPLIER_FAILURE = "ALL_SUPPLIER_FAILURE";

export const SCAN_PRODUCT_REQUEST = "SCAN_PRODUCT_REQUEST";
export const SCAN_PRODUCT_SUCCESS = "SCAN_PRODUCT_SUCCESS";
export const SCAN_PRODUCT_FAILURE = "SCAN_PRODUCT_FAILURE";

export const PRODUCT_INFO_REQUEST = "PRODUCT_INFO_REQUEST";
export const PRODUCT_INFO_SUCCESS = "PRODUCT_INFO_SUCCESS";
export const PRODUCT_INFO_FAILURE = "PRODUCT_INFO_FAILURE";


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";


export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE";

export const GET_HISTORY_DETAILS_REQUEST = "GET_HISTORY_DETAILS_REQUEST";
export const GET_HISTORY_DETAILS_SUCCESS = "GET_HISTORY_DETAILS_SUCCESS";
export const GET_HISTORY_DETAILS_FAILURE = "GET_HISTORY_DETAILS_FAILURE";


export const SEARCH_SUPPLIER_REQUEST = "SEARCH_SUPPLIER_REQUEST";
export const SEARCH_SUPPLIER_SUCCESS = "SEARCH_SUPPLIER_SUCCESS";
export const SEARCH_SUPPLIER_FAILURE = "SEARCH_SUPPLIER_FAILURE";